### ISSUE TITLE
raise: "Did not have permissions for all directories" erros in ubuntu23

### ISSUE THREAD

**Issue by wugeer** [daniejstriata/dust-snap#2]
Hello, my system is Ubuntu 23.04. After installing `dust` from snap, I encountered the following error when running `dust /home/xiehw`: 'Did not have permissions for all directories (add --print-errors to see errors).'
![image](https://github.com/user-attachments/assets/8a7c1ea7-ba1e-4361-b7d2-aeab0a78be8f)
![image](https://github.com/user-attachments/assets/0d69e4cc-325c-47ec-9815-7cedc0ba0c8e)
![image](https://github.com/user-attachments/assets/933d243c-a031-41ab-bc14-a852b9b96cd7)

However, when I built a snap package on my machine based on your snapcraft.yaml (only modifying the package name) and installed it, running `mydust-test.dust /home/xiehw` worked fine.

![image](https://github.com/user-attachments/assets/a2231733-70b0-47f4-bfb8-eb990cbc08d3)
![image](https://github.com/user-attachments/assets/dd01758a-f852-4dfa-96b7-2e081392fb4f)
![image](https://github.com/user-attachments/assets/b7c3156d-ce92-47bd-a58c-3f45e0480477)

Why does the `dust` package installed from the snap repository have this issue? This seems so strange. Could you provide some details about the basic environment where you built the `dust` package that was pushed to the snap repository? Or, if you have time, could you help me look into this issue?

**Comment by danie-dejager** [comment]
When building the package for the global Snap repo, there is some validation done. When you require access to something outside of /home/<user> then Snap is very difficult to get approved. They did not approve my request to allow dust outside of the default containment.

**Comment by wugeer** [comment]
> When building the package for the global Snap repo, there is some validation done. When you require access to something outside of /home/ then Snap is very difficult to get approved. They did not approve my request to allow dust outside of the default containment.

Get!

**Comment by FrostKiwi** [comment]
Big fan of `dust`. This had me seriously confused.

I'd like to add, that this also applies to mixed ownership in general. In my `/home/user/` I have a CI/CD system active, that builds as user `git`. `dust` cannot read them and just refuses to output anything. Doing `sudo dust` or running as `root` in the first place doesn't change this outcome.

`Dust` installed as a sandboxed `snap` really doesn't make sense to me.
Installed it via `wget https://github.com/bootandy/dust/releases/download/v1.1.1/du-dust_1.1.1-1_amd64.deb` + `sudo dpkg -i du-dust_1.1.1-1_amd64.deb` and it worked flawlessly. It should really be in the `apt` repo in the first place, if possible.
